### ISSUE TITLE
Can't install in kde 6

### ISSUE THREAD

**Issue by vuboi** [luisbocanegra/plasma-do-not-unplug-yet#2]
I can't install in kde 6, it show message below:
![image](https://github.com/user-attachments/assets/ef1b25ad-7e97-475f-8298-981f98a827b1)

Environment:

1. Distro: Kde neon
2. Plasma version: 6.1.3
3. Kde frameworks: 6.4.0
4. Qt version: 6.7.2

**Comment by luisbocanegra** [comment]
You can install using `kpackagetool6 -t Plasma/Applet -i package/`

install.sh is looking for some development packages that you don't have installed, that script is mostly for packaging so I should probably switch this and my other addons to kpackagetool6 and have the current install.sh as a separate script like I did in https://github.com/luisbocanegra/plasma-cursor-eyes

**Comment by vuboi** [comment]
Thank you, I have successfully installed it
